CODETOP = ../../..
TARGETTYPE = PROGRAM
OTHER_INCLUDES = -I $(CODETOP)/include -I $(CODETOP)/include/linux -I $(CODETOP)/interface
DEPEND_MODULES = utilities
CPPSOURCES = \
        t2.cpp

include $(CODETOP)/Makefile.def
